services:
  ros2:
    build: .
    container_name: ros2_gz

    network_mode: host   # 🔥 IMPORTANT (better than ports)

    volumes:
      - ./ros2_ws:/workspace              # 🔥 ROS workspace
      - ./supervisord.conf:/etc/supervisor/conf.d/supervisord.conf  # 🔥 hot reload
      - ./nvim:/root/.config/nvim   # 🔥 THIS IS KEY

    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - LIBGL_ALWAYS_SOFTWARE=1
      - QT_QPA_PLATFORM=offscreen

    command: /usr/bin/supervisord

    tty: true
    stdin_open: true