[supervisord]
nodaemon=true

# -----------------------------
# Gazebo
# -----------------------------
[program:gazebo]
priority=10
environment=ROS_USE_SIM_TIME=true
command=/bin/bash -c "export QT_QPA_PLATFORM=offscreen && export QT_QUICK_BACKEND=software && export LIBGL_ALWAYS_SOFTWARE=1 && export GZ_SIM_RENDER_ENGINE=ogre2 && source /opt/ros/jazzy/setup.bash && gz sim -r -s empty.sdf"
autorestart=true
startsecs=5
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0

# -----------------------------
# Bridge
# -----------------------------
[program:bridge]
priority=20
environment=ROS_USE_SIM_TIME=true
command=/bin/bash -c "sleep 5 && source /opt/ros/jazzy/setup.bash && ros2 run ros_gz_bridge parameter_bridge /clock@rosgraph_msgs/msg/Clock@gz.msgs.Clock /cmd_vel@geometry_msgs/msg/Twist@gz.msgs.Twist"
autorestart=true
startsecs=2
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0

# -----------------------------
# Foxglove
# -----------------------------
[program:foxglove]
priority=30
environment=ROS_USE_SIM_TIME=true
command=/bin/bash -c "source /opt/ros/jazzy/setup.bash && ros2 launch foxglove_bridge foxglove_bridge_launch.xml port:=8765 address:=0.0.0.0"
autorestart=true
startsecs=2
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0

# -----------------------------
# LazyVim Dev
# -----------------------------
[program:dev]
priority=40
command=/bin/bash -c "source /opt/ros/jazzy/setup.bash && cd /workspace && nvim"
autostart=false
autorestart=false
stdin_open=true
tty=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr